'use client'

import { useMemo, useState } from 'react'
import {
  Activity, AlertTriangle, ArrowRight, BarChart3, Bell, BookOpen, BrainCircuit, Check, ChevronDown, CircleHelp, ClipboardCheck, Clock3, Download, FileText, Filter, GraduationCap, LayoutDashboard, LifeBuoy, LogOut, Menu, MessageSquare, MoreHorizontal, Search, Settings, ShieldCheck, Sparkles, Target, TrendingUp, Upload, Users, X, Zap,
} from 'lucide-react'

const employeeNav = [
  ['Overview', LayoutDashboard], ['My Competencies', Target], ['Skill Gaps', AlertTriangle], ['Learning Paths', BookOpen], ['Assessments', ClipboardCheck], ['AI Learning Assistant', MessageSquare], ['Learning Materials', FileText], ['Progress', TrendingUp], ['Notifications', Bell],
] as const
const adminNav = [
  ['Dashboard', LayoutDashboard], ['Workforce Intelligence', BrainCircuit], ['Competency Analytics', BarChart3], ['Department Analytics', Activity], ['Training Analytics', GraduationCap], ['Emerging Skill Needs', Zap], ['Employees', Users], ['Learning Content', FileText], ['Assessment Management', ClipboardCheck], ['Reports', Download],
] as const
const skills = [
  { name: 'Survey Design', current: 2.1, required: 4, gap: 'Critical', color: 'critical' },
  { name: 'Sampling Techniques', current: 3.4, required: 4, gap: 'High', color: 'high' },
  { name: 'Data Quality', current: 4, required: 4.5, gap: 'Medium', color: 'medium' },
  { name: 'Statistical Analysis', current: 3.7, required: 4, gap: 'Low', color: 'low' },
  { name: 'Data Visualization', current: 4.2, required: 4.5, gap: 'Low', color: 'low' },
  { name: 'SDG Indicators', current: 2.8, required: 4, gap: 'Medium', color: 'medium' },
]
const courses = [
  ['Advanced Survey Methodology', 'Survey Design', 'Intermediate', '4h 20m', 'iGOT Karmayogi', 42],
  ['Sampling Methods for Official Statistics', 'Sampling Techniques', 'Intermediate', '3h 10m', 'MoSPI Academy', 18],
  ['Data Quality Frameworks', 'Data Quality', 'Foundational', '2h 45m', 'UN Statistics Division', 67],
]

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="brand"><span className="brand-mark"><span /><span /><span /></span>{!compact && <span><b>StatSkill</b><small>INTELLIGENCE</small></span>}</div>
}
function StatusBadge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span> }
function ProgressBar({ value, tone = 'blue' }: { value: number; tone?: string }) { return <div className="progress"><span className={tone} style={{ width: `${Math.min(value, 100)}%` }} /></div> }
function Kpi({ label, value, note, icon: Icon, tone = 'blue' }: { label: string; value: string; note: string; icon: any; tone?: string }) { return <div className="kpi"><div className={`kpi-icon ${tone}`}><Icon size={18} /></div><div><p>{label}</p><strong>{value}</strong><small className={note.startsWith('+') ? 'positive' : ''}>{note}</small></div></div> }
function LoopStrip() { return <div className="loop-strip">{['PROFILE','ASSESS','MEASURE','IDENTIFY GAPS','LEARN','REASSESS','UPDATE'].map((item, i) => <div key={item} className={i === 0 ? 'active' : ''}><span>{i + 1}</span>{item}{i < 6 && <ArrowRight size={13} />}</div>)}</div> }
function BarComparison({ skill }: { skill: typeof skills[number] }) { return <div className="skill-row"><div className="skill-label"><span>{skill.name}</span><b>{skill.current.toFixed(1)} <em>/ {skill.required.toFixed(1)}</em></b></div><div className="compare"><span className="required" style={{ width: `${skill.required / 5 * 100}%` }} /><span className="current" style={{ width: `${skill.current / 5 * 100}%` }} /></div></div> }
function MiniLine() { return <svg className="mini-line" viewBox="0 0 300 100" preserveAspectRatio="none" aria-label="Competency growth chart"><path d="M0 78 C25 72 38 76 54 64 S83 68 100 55 S127 58 145 47 S176 48 192 35 S218 36 236 28 S270 22 300 10" fill="none" stroke="var(--primary)" strokeWidth="3" /><path d="M0 78 C25 72 38 76 54 64 S83 68 100 55 S127 58 145 47 S176 48 192 35 S218 36 236 28 S270 22 300 10 V100 H0Z" fill="url(#fill)" opacity=".12" /><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="var(--primary)" /><stop offset="1" stopColor="transparent" /></linearGradient></defs></svg> }

export default function Page() {
  const [role, setRole] = useState<'employee' | 'admin'>('employee')
  const [view, setView] = useState('Overview')
  const [mobileOpen, setMobileOpen] = useState(false)
  const nav = role === 'employee' ? employeeNav : adminNav
  const title = view === 'Overview' ? 'Good morning, Rahul' : view
  const sub = view === 'Overview' ? "Here's your competency and learning overview." : role === 'admin' ? 'Organization-wide competency and learning insights.' : 'Understand what you know, what you need, and what to learn next.'
  const filteredSkills = useMemo(() => skills, [])
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
      <div className="sidebar-top"><Logo /><button className="mobile-close" onClick={() => setMobileOpen(false)}><X size={18} /></button></div>
      <div className="workspace"><span className="workspace-dot" /><div><small>OFFICIAL STATISTICS SYSTEM</small><b>{role === 'employee' ? 'Employee workspace' : 'Administrator workspace'}</b></div><ChevronDown size={15} /></div>
      <nav><p className="nav-label">{role === 'employee' ? 'MY WORKSPACE' : 'ADMINISTRATION'}</p>{nav.map(([label, Icon]) => <button key={label} className={view === label ? 'nav-item active' : 'nav-item'} onClick={() => { setView(label); setMobileOpen(false) }}><Icon size={17} />{label}{label === 'Notifications' && <span className="nav-count">3</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="security"><ShieldCheck size={16} /><span><b>Secure environment</b><small>Authorized personnel only</small></span></div><button className="nav-item"><Settings size={17} />Settings</button><button className="nav-item"><LogOut size={17} />Sign out</button><div className="user"><div className="avatar">RK</div><span><b>Rahul Kumar</b><small>Statistical Officer</small></span><MoreHorizontal size={18} /></div></div>
    </aside>
    <main className="main"><header className="topbar"><button className="menu-btn" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><div className="breadcrumb"><span>StatSkill Intelligence</span><ArrowRight size={14} /><b>{view}</b></div><div className="top-actions"><button className="icon-btn" aria-label="Help"><CircleHelp size={18} /></button><button className="icon-btn notification" aria-label="Notifications"><Bell size={18} /><i /></button><div className="role-switch"><button className={role === 'employee' ? 'selected' : ''} onClick={() => { setRole('employee'); setView('Overview') }}>Employee</button><button className={role === 'admin' ? 'selected' : ''} onClick={() => { setRole('admin'); setView('Dashboard') }}>Admin</button></div></div></header>
      <div className="content"><div className="page-head"><div><div className="eyebrow"><span className="live-dot" />LIVE COMPETENCY INTELLIGENCE</div><h1>{title}</h1><p>{sub}</p></div><div className="head-actions"><button className="btn secondary"><Download size={16} /> Export report</button><button className="icon-btn"><MoreHorizontal size={19} /></button></div></div>
      {role === 'admin' ? <AdminView view={view} /> : <EmployeeView view={view} skills={filteredSkills} />}
      </div></main>
  </div>
}

function EmployeeView({ view, skills }: { view: string; skills: typeof skills }) {
  if (view === 'AI Learning Assistant') return <Assistant />
  if (view === 'Learning Materials') return <Materials />
  if (view === 'Assessments') return <Assessment />
  if (view === 'Learning Paths') return <LearningPath />
  if (view === 'Skill Gaps') return <SkillGaps skills={skills} />
  if (view === 'My Competencies') return <CompetencyProfile skills={skills} />
  if (view === 'Progress') return <ProgressView />
  if (view === 'Notifications') return <Notifications />
  return <><LoopStrip /><section className="kpi-grid"><Kpi label="Overall competency" value="78%" note="+6% from last assessment" icon={Target} /><Kpi label="Competencies assessed" value="24 / 30" note="6 remaining" icon={ClipboardCheck} tone="indigo" /><Kpi label="Learning progress" value="68%" note="12h 40m this month" icon={BookOpen} tone="green" /><Kpi label="Assessment readiness" value="82%" note="Ready for reassessment" icon={Zap} tone="amber" /></section><div className="dashboard-grid"><section className="card competency-card"><div className="card-head"><div><h2>Competency overview</h2><p>Current level compared to role requirements</p></div><button className="text-btn">View profile <ArrowRight size={15} /></button></div><div className="legend"><span><i className="legend-current" />Current level</span><span><i className="legend-required" />Required level</span></div>{skills.map(s => <BarComparison key={s.name} skill={s} />)}</section><section className="card trend-card"><div className="card-head"><div><h2>Competency trajectory</h2><p>Growth across your last 6 assessments</p></div><StatusBadge tone="positive">+6.0%</StatusBadge></div><div className="trend-value"><strong>3.9</strong><span>/ 5.0 average level</span></div><MiniLine /><div className="chart-axis"><span>Jan</span><span>Mar</span><span>May</span><span>Jul 2026</span></div><div className="insight"><Sparkles size={16} /><span><b>Good momentum.</b> Your strongest growth is in Data Visualization.</span></div></section></div><section className="lower-grid"><div className="card gaps-card"><div className="card-head"><div><h2>Top skill gaps</h2><p>Prioritized by impact on your role</p></div><button className="text-btn">See all <ArrowRight size={15} /></button></div>{skills.slice(0, 3).map(s => <div className="gap-item" key={s.name}><div className={`severity ${s.color}`}><AlertTriangle size={15} /></div><div className="gap-copy"><div><b>{s.name}</b><StatusBadge tone={s.color}>{s.gap}</StatusBadge></div><small>Current {s.current.toFixed(1)} <span>Required {s.required.toFixed(1)}</span></small><ProgressBar value={s.current / s.required * 100} tone={s.color} /></div><strong className="gap-number">-{(s.required - s.current).toFixed(1)}</strong></div>)}</div><div className="card next-card"><div className="card-head"><div><h2>Recommended for you</h2><p>Based on your competency profile</p></div><Sparkles size={18} className="blue-icon" /></div>{courses.slice(0, 2).map(c => <CourseRow key={c[0]} course={c} />)}</div></section></>
}
function CourseRow({ course }: { course: (string | number)[] }) { return <div className="course-row"><div className="course-icon"><BookOpen size={17} /></div><div className="course-info"><b>{course[0]}</b><small>{course[1]} · {course[2]} · {course[3]}</small><div className="course-meta"><span>{course[4]}</span><span>{course[5]}% complete</span></div><ProgressBar value={Number(course[5])} /></div><button className="round-arrow" aria-label="Open course"><ArrowRight size={16} /></button></div> }
function SkillGaps({ skills }: { skills: typeof skills }) { return <><div className="stat-row"><div><small>ROLE</small><b>Statistical Officer</b></div><div><small>COMPETENCY MATCH</small><b className="blue-text">78%</b></div><div><small>CRITICAL GAPS</small><b className="red-text">3</b></div><div><small>MODERATE GAPS</small><b className="amber-text">6</b></div></div><div className="filter-row"><div className="filter-tabs"><button className="active">All gaps <span>12</span></button><button>Critical</button><button>High</button><button>Medium</button><button>Low</button></div><button className="btn secondary"><Filter size={15} /> By competency domain</button></div><section className="card"><div className="card-head"><div><h2>Current competency vs required</h2><p>Role requirements mapped to your latest evidence</p></div><StatusBadge tone="neutral">Last assessed 18 Aug 2026</StatusBadge></div>{skills.map(s => <BarComparison key={s.name} skill={s} />)}</section><section className="why-grid"><div className="card why-card"><div className="eyebrow">SELECTED GAP · CRITICAL</div><h2>Why this gap matters</h2><h3>Survey Design</h3><p>This competency is essential for designing reliable statistical surveys and directly affects data quality and representativeness.</p><div className="why-metrics"><div><small>Current level</small><b>1.8 / 5</b></div><div><small>Required level</small><b>4.0 / 5</b></div><div><small>Gap</small><b className="red-text">2.2 pts</b></div></div></div><div className="card"><div className="card-head"><div><h2>Next best action</h2><p>AI-recommended intervention</p></div><Sparkles size={18} className="blue-icon" /></div><h3>Advanced Survey Methodology</h3><p>Complete the learning path to build foundational and applied capability.</p><div className="action-meta"><span><Clock3 size={14} /> 4h 20m</span><span><TrendingUp size={14} /> +1.4 predicted</span></div><button className="btn primary">Start learning <ArrowRight size={15} /></button></div></section></> }
function CompetencyProfile({ skills }: { skills: typeof skills }) { return <><div className="profile-banner"><div className="avatar large">RK</div><div><h2>Rahul Kumar</h2><p>Statistical Officer · Survey Statistics</p><div className="profile-tags"><StatusBadge tone="positive">Active profile</StatusBadge><span>6 years experience</span><span>Joined Jan 2020</span></div></div><button className="btn secondary">Edit profile</button></div><section className="kpi-grid"><Kpi label="Overall competency" value="78%" note="+6% from last assessment" icon={Target} /><Kpi label="Competencies assessed" value="24 / 30" note="6 remaining" icon={ClipboardCheck} tone="indigo" /><Kpi label="Learning hours" value="48.5h" note="This financial year" icon={Clock3} tone="green" /><Kpi label="Profile confidence" value="High" note="Based on 24 evidence points" icon={ShieldCheck} tone="amber" /></section><section className="card table-card"><div className="card-head"><div><h2>Competency matrix</h2><p>Latest verified evidence by competency</p></div><button className="btn secondary"><Download size={15} /> Export</button></div><div className="table-wrap"><table><thead><tr><th>Competency</th><th>Current level</th><th>Required</th><th>Gap</th><th>Confidence</th><th>Last assessed</th></tr></thead><tbody>{skills.concat([{ name: 'National Accounts', current: 3.8, required: 4, gap: 'Low', color: 'low' }, { name: 'Price Statistics', current: 3.2, required: 4, gap: 'Medium', color: 'medium' }]).map(s => <tr key={s.name}><td><b>{s.name}</b></td><td><strong>{s.current.toFixed(1)}</strong> / 5</td><td>{s.required.toFixed(1)}</td><td><StatusBadge tone={s.color}>{(s.required - s.current).toFixed(1)} gap</StatusBadge></td><td><span className="confidence"><i /> High</span></td><td className="muted">18 Aug 2026</td></tr>)}</tbody></table></div></section></> }
function LearningPath() { return <><section className="card path-card"><div className="card-head"><div><h2>Survey Design mastery path</h2><p>AI-curated based on your largest competency gap</p></div><StatusBadge tone="positive">32% complete</StatusBadge></div><div className="roadmap">{['Survey Design Fundamentals','Sampling Methodology','Advanced Survey Design','Assessment','Competency re-evaluation'].map((s, i) => <div className={`road-step ${i < 2 ? 'done' : i === 2 ? 'current' : ''}`} key={s}><div className="step-marker">{i < 2 ? <Check size={15} /> : i + 1}</div>{i < 4 && <div className="step-line" />}<div className="step-content"><b>{s}</b><small>{i < 2 ? 'Completed' : i === 2 ? 'In progress' : 'Upcoming'} · {i === 2 ? '4h 20m' : '2h 30m'}</small><span>{i === 0 ? 'Survey Design' : i === 1 ? 'Sampling Techniques' : 'Survey Design'}</span></div>{i === 2 && <ProgressBar value={42} />}</div>)}</div></section><section className="card ai-recommend"><div className="ai-symbol"><Sparkles size={19} /></div><div><div className="eyebrow">AI RECOMMENDATION</div><h2>Why this path?</h2><p>Your largest competency gap is <b>Survey Design</b>. Completing these modules is predicted to improve your competency from Level 2 to Level 3.5.</p></div><button className="btn primary">Continue path <ArrowRight size={15} /></button></section><div className="section-head"><div><h2>More learning for your role</h2><p>Curated from official learning providers</p></div><button className="text-btn">Browse library <ArrowRight size={15} /></button></div><div className="course-grid">{courses.map(c => <div className="card course-card" key={c[0]}><div className="course-cover"><BookOpen size={22} /><span>OFFICIAL LEARNING</span></div><h3>{c[0]}</h3><p>Build practical capability through guided lessons and applied examples.</p><div className="course-tags"><StatusBadge tone="neutral">{c[1]}</StatusBadge><span>{c[3]}</span></div><button className="btn secondary full">View course <ArrowRight size={15} /></button></div>)}</div></> }
function Assistant() { const [message, setMessage] = useState(''); const [sent, setSent] = useState(false); return <div className="assistant-layout"><aside className="conversation card"><div className="card-head"><h2>Conversations</h2><button className="icon-btn"><MoreHorizontal size={17} /></button></div><button className="new-chat"><MessageSquare size={15} /> New conversation</button>{['Stratified sampling explained','Survey methodology notes','Practice assessment · Data quality'].map((x, i) => <button className={`conversation-item ${i === 0 ? 'active' : ''}`} key={x}><MessageSquare size={15} /><span>{x}<small>{i === 0 ? 'Today, 10:42 AM' : 'Yesterday'}</small></span></button>)}</aside><section className="chat card"><div className="chat-head"><div className="ai-avatar"><BrainCircuit size={18} /></div><div><h2>StatSkill Assistant</h2><p><span className="live-dot" />Grounded in: Survey_Methodology.pdf</p></div><StatusBadge tone="positive">Verified sources</StatusBadge></div><div className="messages"><div className="message user-message">Explain stratified sampling in simple terms.</div><div className="message ai-message"><div className="ai-avatar small"><BrainCircuit size={14} /></div><div><p>Stratified sampling is a method where you divide a population into smaller groups — called strata — based on shared characteristics, such as region or age. You then select a sample from each group.</p><p>This helps ensure every important subgroup is represented in your final results, making estimates more reliable.</p><div className="source"><FileText size={13} /><span>Survey_Methodology.pdf · Page 24</span></div></div></div>{sent && <div className="message user-message">{message}</div>}</div><div className="suggestions"><span>Suggested prompts</span><button onClick={() => setMessage('Give me an example')}>Give me an example</button><button onClick={() => setMessage('Test my understanding')}>Test my understanding</button><button onClick={() => setMessage('Generate 5 MCQs')}>Generate 5 MCQs</button></div><div className="composer"><input value={message} onChange={e => setMessage(e.target.value)} placeholder="Ask about your learning material..." onKeyDown={e => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229 && message) { setSent(true); setMessage('') } }} /><button className="btn primary square" onClick={() => { if (message) { setSent(true); setMessage('') } }}><ArrowRight size={17} /></button></div></section></div> }
function Materials() { return <><section className="upload-layout"><div className="card upload-card"><div className="upload-zone"><div className="upload-icon"><Upload size={20} /></div><h2>Drop learning material here</h2><p>Upload PDF, PPT, DOCX or TXT files up to 50 MB</p><button className="btn secondary">Browse files</button></div><div className="file-preview"><div className="file-icon"><FileText size={19} /></div><div><b>Survey_Methodology.pdf</b><small>86 pages · Uploaded just now</small></div><StatusBadge tone="positive">Ready</StatusBadge><button className="icon-btn"><X size={16} /></button></div></div><div className="card config-card"><div className="eyebrow">AI CONFIGURATION</div><h2>Generate assessment</h2><p>Configure how StatSkill AI should test this material.</p><label>Number of questions<select><option>10 questions</option><option>20 questions</option></select></label><label>Difficulty<select><option>Adaptive</option><option>Foundational</option><option>Advanced</option></select></label><label>Question types<div className="check-row"><StatusBadge tone="blue">MCQ</StatusBadge><StatusBadge tone="neutral">True / False</StatusBadge><StatusBadge tone="neutral">Scenario-based</StatusBadge></div></label><label>Target competency<select><option>Survey Design</option><option>Sampling Techniques</option></select></label><button className="btn primary full"><Sparkles size={16} /> Generate assessment</button></div></section><section className="card detected-card"><div className="card-head"><div><h2>Material intelligence</h2><p>AI-detected concepts and competency mapping</p></div><StatusBadge tone="positive">Analysis complete</StatusBadge></div><div className="detected-grid"><div><small>DETECTED TOPICS</small><div className="tag-list">{['Sampling','Survey Design','Data Collection','Non-response','Weighting'].map(x => <StatusBadge tone="neutral" key={x}>{x}</StatusBadge>)}</div></div><div><small>DETECTED COMPETENCIES</small><div className="tag-list">{['Survey Design','Sampling Techniques','Data Quality'].map(x => <StatusBadge tone="blue" key={x}>{x}</StatusBadge>)}</div></div></div></section></> }
function Assessment() { const [selected, setSelected] = useState(''); return <><div className="assessment-top"><div><StatusBadge tone="blue">INTERMEDIATE</StatusBadge><h2>Assessment: Survey Methodology</h2><p>Question 4 of 10 · Competency: Sampling Techniques</p></div><div className="timer"><Clock3 size={16} /><b>08:42</b><small>Time remaining</small></div></div><div className="assessment-layout"><section className="card question-card"><div className="question-progress"><span>4 of 10</span><ProgressBar value={40} /></div><h2>Which sampling approach is most appropriate when the population is divided into distinct subgroups and representation from each subgroup is required?</h2><div className="options">{['Simple random sampling','Stratified sampling','Systematic sampling','Cluster sampling'].map((x, i) => <button className={selected === x ? 'option selected' : 'option'} onClick={() => setSelected(x)} key={x}><span>{String.fromCharCode(65 + i)}</span>{x}{selected === x && <Check size={17} />}</button>)}</div><div className="question-actions"><button className="btn secondary">Previous</button><button className="btn ghost"><FlagIcon /> Flag question</button><button className="btn primary">Next <ArrowRight size={15} /></button></div></section><aside className="card assessment-side"><h3>Assessment progress</h3><div className="question-grid">{Array.from({ length: 10 }, (_, i) => <span className={i < 3 ? 'answered' : i === 3 ? 'active' : ''} key={i}>{i + 1}</span>)}</div><div className="assessment-legend"><span><i className="answered" />Answered</span><span><i className="active" />Current</span><span><i />Not answered</span></div></aside></div></> }
function FlagIcon() { return <span className="flag-shape" /> }
function ProgressView() { return <><section className="kpi-grid"><Kpi label="Learning hours" value="48.5h" note="+12.4h this quarter" icon={Clock3} tone="green" /><Kpi label="Courses completed" value="14" note="3 this month" icon={BookOpen} /><Kpi label="Assessments completed" value="18" note="82% average score" icon={ClipboardCheck} tone="indigo" /><Kpi label="Competencies improved" value="9" note="Since Jan 2026" icon={TrendingUp} tone="amber" /></section><div className="dashboard-grid"><section className="card trend-card wide"><div className="card-head"><div><h2>Competency growth over time</h2><p>Your average competency score across assessments</p></div><button className="btn secondary">Last 12 months <ChevronDown size={15} /></button></div><div className="big-trend"><strong>3.9</strong><span><b>+0.8</b> improvement</span></div><MiniLine /><div className="chart-axis"><span>Sep 25</span><span>Dec 25</span><span>Mar 26</span><span>Jun 26</span><span>Aug 26</span></div></section><section className="card"><div className="card-head"><div><h2>Before → after</h2><p>Impact of learning interventions</p></div></div>{[['Survey Design','2.1','3.7'],['Sampling','2.8','4.0'],['Data Quality','3.2','4.1']].map(x => <div className="before-after" key={x[0]}><div><b>{x[0]}</b><span>{x[1]} <ArrowRight size={13} /> <strong>{x[2]}</strong></span></div><ProgressBar value={Number(x[2]) / 5 * 100} tone="green" /></div>)}</section></div><section className="card milestones"><div className="card-head"><div><h2>Professional milestones</h2><p>Evidence of your continuous development</p></div></div><div className="milestone-row">{[['18 Aug','Sampling reassessment','Level improved to 4.0'],['02 Aug','Completed 10th course','48.5 learning hours'],['14 Jun','Profile verified','24 competencies assessed']].map(x => <div key={x[0]}><b>{x[0]}</b><span><i /><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</div></section></> }
function Notifications() { return <section className="card notifications-card"><div className="card-head"><div><h2>Notifications</h2><p>Stay up to date with your competency journey</p></div><button className="text-btn">Mark all as read</button></div>{[['critical','Assessment due','Your Survey Design competency assessment is due.','Today, 9:20 AM'],['blue','New recommendation','New course recommended based on your recent assessment.','Yesterday, 4:15 PM'],['positive','Competency improved','You improved from Level 2.8 to Level 3.6 in Sampling.','18 Aug 2026'],['amber','Mandatory training','Your department has a new mandatory training module.','14 Aug 2026']].map(x => <div className="notification-row" key={x[1]}><div className={`notification-dot ${x[0]}`}><Bell size={16} /></div><div><b>{x[1]}</b><p>{x[2]}</p><small>{x[3]}</small></div><ArrowRight size={16} /></div>)}</section> }

function AdminView({ view }: { view: string }) { if (view === 'Employees') return <Employees />; if (view === 'Emerging Skill Needs') return <Emerging />; if (view === 'Reports') return <Reports />; return <><div className="admin-banner"><div><div className="eyebrow"><span className="live-dot" />NATIONAL WORKFORCE VIEW</div><h2>Intelligence across India's statistical workforce</h2><p>Monitor competency health, identify emerging needs, and direct learning investment where it matters most.</p></div><div className="admin-date">As of 27 Aug 2026<br /><span>Data refreshes daily</span></div></div><section className="kpi-grid"><Kpi label="Employees" value="1,248" note="Across 8 departments" icon={Users} /><Kpi label="Average competency" value="74%" note="+4% this quarter" icon={Target} tone="indigo" /><Kpi label="Critical skill gaps" value="186" note="-12% from last month" icon={AlertTriangle} tone="red" /><Kpi label="Training completion" value="68%" note="+8% this quarter" icon={GraduationCap} tone="green" /></section><div className="dashboard-grid"><section className="card distribution"><div className="card-head"><div><h2>Workforce competency distribution</h2><p>Employees by current competency level</p></div><button className="btn secondary">All departments <ChevronDown size={15} /></button></div><div className="distribution-chart"><div className="donut"><div><strong>74%</strong><small>Average</small></div></div><div className="dist-legend">{[['Advanced','286','18%','high'],['Proficient','548','44%','blue'],['Developing','332','27%','medium'],['Foundational','82','7%','critical']].map(x => <div key={x[0]}><i className={x[3]} /><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></div></section><section className="card common-gaps"><div className="card-head"><div><h2>Most common skill gaps</h2><p>Across all assessed employees</p></div><StatusBadge tone="neutral">Top 5</StatusBadge></div>{[['Survey Design',68],['Data Quality',54],['Sampling',47],['SDG Indicators',39],['Statistical Analysis',31]].map(x => <div className="admin-bar" key={x[0]}><div><span>{x[0]}</span><b>{x[1]}%</b></div><ProgressBar value={x[1]} tone={x[1] > 60 ? 'critical' : x[1] > 45 ? 'medium' : 'blue'} /></div>)}</section></div><section className="card department-card"><div className="card-head"><div><h2>Critical gaps by department</h2><p>Employees with one or more critical competency gaps</p></div><button className="text-btn">View department analytics <ArrowRight size={15} /></button></div><div className="dept-grid">{[['Agriculture','48'],['Labour','41'],['Industry','36'],['National Accounts','29'],['Price Statistics','22']].map(x => <div key={x[0]}><span>{x[0]}</span><b>{x[1]} <small>employees</small></b><ProgressBar value={Number(x[1]) / 48 * 100} tone="critical" /></div>)}</div></section></> }
function Employees() { return <><div className="toolbar"><div className="searchbox"><Search size={16} /><input placeholder="Search employees..." /></div><button className="btn secondary"><Filter size={15} /> Filters</button><button className="btn secondary">Department <ChevronDown size={15} /></button></div><section className="card table-card"><div className="card-head"><div><h2>Employee directory</h2><p>1,248 employees across the official statistical system</p></div><StatusBadge tone="positive">Live data</StatusBadge></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Designation</th><th>Department</th><th>Competency</th><th>Critical gaps</th><th>Learning progress</th><th>Status</th></tr></thead><tbody>{[['Anita Sharma','Deputy Director','Agriculture','86%','0','82%','On track'],['Rahul Kumar','Statistical Officer','Survey Statistics','78%','3','68%','Needs focus'],['Vikram Singh','Assistant Director','Labour','72%','2','54%','In progress'],['Meera Nair','Statistical Officer','National Accounts','81%','1','76%','On track'],['Sanjay Gupta','Research Officer','Industry','64%','4','42%','At risk']].map(x => <tr key={x[0]}><td><div className="employee-cell"><div className="avatar small">{x[0].split(' ').map(a => a[0]).join('')}</div><b>{x[0]}</b></div></td><td>{x[1]}</td><td>{x[2]}</td><td><strong>{x[3]}</strong></td><td><StatusBadge tone={Number(x[4]) > 2 ? 'critical' : Number(x[4]) > 0 ? 'medium' : 'positive'}>{x[4]}</StatusBadge></td><td><div className="table-progress"><ProgressBar value={Number(x[5].replace('%',''))} />{x[5]}</div></td><td><StatusBadge tone={x[6] === 'On track' ? 'positive' : x[6] === 'At risk' ? 'critical' : 'medium'}>{x[6]}</StatusBadge></td></tr>)}</tbody></table></div></section></> }
function Emerging() { return <><section className="emerging-hero card"><div className="emerging-icon"><Zap size={23} /></div><div><div className="eyebrow">AI STRATEGIC SIGNAL · HIGH CONFIDENCE</div><h2>Data Quality & Validation</h2><p>Emerging competency requirement identified from workforce evidence and departmental plans.</p></div><StatusBadge tone="high">↑ 23% in 6 months</StatusBadge></section><section className="kpi-grid"><Kpi label="Affected departments" value="5" note="Of 8 departments" icon={Users} /><Kpi label="Employees affected" value="312" note="25% of workforce" icon={Target} tone="amber" /><Kpi label="Evidence confidence" value="92%" note="Based on 4 signals" icon={ShieldCheck} tone="green" /><Kpi label="Priority" value="High" note="Action recommended" icon={AlertTriangle} tone="red" /></section><div className="dashboard-grid"><section className="card trend-card wide"><div className="card-head"><div><h2>Emerging need trend</h2><p>Identified gaps over the last 6 months</p></div></div><div className="big-trend"><strong>312</strong><span><b className="red-text">+23%</b> employees affected</span></div><MiniLine /><div className="chart-axis"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></section><section className="card action-card"><div className="eyebrow">RECOMMENDED ORGANIZATIONAL ACTION</div><h2>Launch targeted Data Quality training</h2><p>Prioritize affected departments and align learning content with the updated competency framework.</p><button className="btn primary">Create learning initiative <ArrowRight size={15} /></button></section></div></> }
function Reports() { return <><div className="toolbar"><div className="searchbox"><Search size={16} /><input placeholder="Search reports..." /></div><button className="btn primary"><Download size={15} /> Export selected</button></div><div className="report-grid">{[['Workforce competency report','Organization-wide competency levels, gaps, and trends.','Updated today'],['Department skill gap report','Critical competency gaps by department and role.','Updated yesterday'],['Training effectiveness report','Learning completion and competency improvement outcomes.','Updated 18 Aug'],['Assessment performance report','Assessment scores, reliability, and coverage.','Updated 18 Aug'],['Emerging skill report','AI-identified future competency requirements.','Updated 27 Aug']].map((x, i) => <div className="card report-card" key={x[0]}><div className="report-icon"><FileText size={20} /></div><div><h3>{x[0]}</h3><p>{x[1]}</p><small>{x[2]}</small></div><button className="icon-btn"><Download size={16} /></button></div>)}</div></> }
